name: dart_advanced
description: A sample command-line application.
version: 0.0.1

environment:
  sdk: '>=2.9.0'

dependencies:
  path: ^1.7.0
  archive: ^2.0.13
  pointycastle: ^1.0.2
  collection: any
  sqljocky5: ^2.2.1

dev_dependencies:
  test: ^1.15.3
